//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eClinic
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitDisease
    {
        public int Id { get; set; }
        public Nullable<int> Visit_ID { get; set; }
        public Nullable<int> Diseases_ID { get; set; }
    }
}
